class Data {
  
  static List<String> nameList = [
    'Mastodon',
    'Casual',
    'The Box Tops',
    'Northern Lights',
    'Sonora Santanera',
    'Adam Ant',
    'Gob',
    'Jeff And Sheri Easter',
    'Rated R',
    'Tweeterfriendly Music',
    'Planet P Project',
    'Clp',
    'JennyAnyKind',
    'Wayne Watson',
    'Andy Andy',
    'Bob Azzam',
    'Lionel Richie',
    'Blue Rodeo',
    'Richard Souther',
    'Faiz Ali Faiz',
    'Tesla',
    'lextrical',
    'Jimmy Wakely',
    'Alice Stuart',
    'Elena',
    'The Dillinger Escape Plan',
    'SUE THOMPSON',
    'Five Bolt Main',
    'Clp',
    'Tim Wilson',
    'Willie Bobo',
    'Faye Adams',
    'Terry Callier',
    'John Wesley',
    'The Shangri-Las',
    'Billie Jo Spears',
    'Sierra Maestra',
    'Ocean Surfers',
    'Despina Vandi',
    'Javier Navarrete',
    'Jacob Young',
    'Scarlet\'s Remains',
    'The Suicide Machines',
    'The Rolling Stones',
    'Roberto Torres',
    'Loudon Wainwright III',
    'R.L. Burnside',
    'Stevie Ray Vaughan',
    'John Hammond',
    'Casiotone For The Painfully Alone',
    'Ec8or',
    'The New York Dolls',
    'Eliane Elias',
    'Lost Boyz',
    'The Germs',
    'Yamandu Costa',
    'Chris Rea',
    'Perrey And Kingsley',
    'Eurythmics'
  ];
  static List<String> artistList = [
    'Deep Sea Creature',
    'I Didn\'t Mean To',
    'Soul Deep',
    'Cjbeards',
    'Amor De Cabaret',
    'Something Girls',
    'Face the Ashes',
    'The Moon And I (Ordinary Day Album Version)',
    'Keepin It Real (Skit)',
    'Drop of Rain',
    'Pink World',
    'Insatiable (Instrumental Version)',
    'Young Boy Blues',
    'The Urgency (LP Version)',
    'La Culpa',
    'Auguri Cha Cha',
    'Tonight Will Be Alright',
    'Floating',
    'High Tide',
    'Sohna Nee Sohna Data',
    'Caught In A Dream',
    'Synthetic Dream',
    'Broken-Down Merry-Go-Round',
    'Kassie Jones',
    'Setanta matins',
    'Setting Fire to Sleeping Giants',
    'James (Hold The Ladder Steady)',
    'Made Like This (Live)',
    'Superconfidential',
    'I Think My Wife Is Running Around On Me (Taco Hell)',
    'Spanish Grease',
    'Crazy Mixed Up World',
    'Do You Finally Need A Friend',
    'The Emperor Falls',
    'Twist and Shout',
    'It Makes No Difference Now',
    'Laws Patrolling (Album Version)',
    'Barking Dogs (From Piouhgd)',
    'OUTE ENA EFHARISTO',
    'Midnight Swim',
    'In A Subtle Way',
    'Spin',
    'Burning In The Aftermath',
    'Angie (1993 Digital Remaster)',
    'Sabor Guajiro',
    'Human Cannonball',
    'Glory Be',
    'Crossfire',
    'I Can\'t Be Satisfied',
    'Nashville Parthenon',
    'Cocain Ducks',
    'Human Being',
    'The More I See You',
    'Certain Things We Do',
    'Forming',
    'Mafu\xc3\xa1',
    'Driving Home For Christmas',
    'Spooks In Space',
    'Tous Les Gar\xc3\xa7ons Et Les Filles'
  ];
}
